2024-11-21 18:53:02,180 - INFO - Training configuration:
2024-11-21 18:53:02,180 - INFO - num_points: 4096
2024-11-21 18:53:02,180 - INFO - chunk_size: 4096
2024-11-21 18:53:02,180 - INFO - overlap: 1024
2024-11-21 18:53:02,180 - INFO - batch_size: 64
2024-11-21 18:53:02,180 - INFO - num_workers: 0
2024-11-21 18:53:02,180 - INFO - learning_rate: 0.001
2024-11-21 18:53:02,180 - INFO - num_classes: 5
2024-11-21 18:53:02,180 - INFO - num_epochs: 500
2024-11-21 18:53:02,180 - INFO - device: cuda
2024-11-21 18:53:02,180 - INFO - Using device: cuda
2024-11-21 18:53:02,180 - INFO - Loading train data...
2024-11-21 18:53:08,647 - INFO - reading train data
2024-11-21 18:53:08,647 - INFO - Loading val data...
2024-11-21 18:53:09,643 - INFO - reading val data
2024-11-21 18:53:09,643 - INFO - Train dataset size: 6
2024-11-21 18:53:09,643 - INFO - Val dataset size: 1
2024-11-21 18:53:10,424 - INFO - Total samples is: <torch.utils.data.dataloader.DataLoader object at 0x000001EC07E2C110>
2024-11-21 18:53:10,457 - ERROR - Training failed with exception:
Traceback (most recent call last):
  File "D:\Work\Pointcloud-WL\Pointcloud-bridge\Highway_bridge\train.py", line 320, in <module>
    train()
  File "D:\Work\Pointcloud-WL\Pointcloud-bridge\Highway_bridge\train.py", line 133, in train
    for batch in pbar:
  File "C:\Users\cy519\anaconda3\envs\pytorch\Lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Users\cy519\anaconda3\envs\pytorch\Lib\site-packages\torch\utils\data\dataloader.py", line 701, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\cy519\anaconda3\envs\pytorch\Lib\site-packages\torch\utils\data\dataloader.py", line 757, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cy519\anaconda3\envs\pytorch\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "D:\Work\Pointcloud-WL\Pointcloud-bridge\Highway_bridge\utils\data_utils.py", line 136, in __getitem__
    points, colors = self.apply_transform(points.numpy(), colors.numpy())
                                          ^^^^^^^^^^^^
AttributeError: 'numpy.ndarray' object has no attribute 'numpy'. Did you mean: 'dump'?
